GET http://localhost/api/1/list
Accept: application/json
Authorization: Bearer 1|mi9vArb9c64Epm83AyOHxeeBB2dCsw9bGrVoz2u5

###


POST http://localhost/api/3/send
Content-Type: application/json
Authorization: Bearer 1|mi9vArb9c64Epm83AyOHxeeBB2dCsw9bGrVoz2u5

{
  "email" : "ucha19871@gmail.com",
  "subject" : "test subject 5",
  "body" : "test body 5"
}

###
